[[main]]
  identifier = "about"
  name = "About"
  url = "about"
  weight = 2

[[main]]
  identifier = "posts"
  name = "All Posts"
  url = "posts"
  weight = 1

[[main]]
  identifier = "archive"
  name = "Archive"
  url = "archive"
  weight = 3

[[main]]
  identifier = "Contact"
  name = "Contact"
  url = "contact"
  weight = 4